from django.conf.urls import patterns, url, include
from django.views.generic import RedirectView
from o_fastrax.fastrax.views import *
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = patterns('o_fastrax.fastrax.views',
    url(r'^$', 'index', name='index'),
    (r'^search/$', 'search'),
    (r'^upcoming/$', 'upcoming'),
    (r'^register/$', 'register'),
    url(r'^smokeregister/$', (ListSmokeRegister.as_view()), name='list_smokeregister'),
    url(r'^smokeregister/create/$', permission_required('fastrax.add_smokeregister')(CreateSmokeRegister.as_view()), name='create_smokeregister'),
    url(r'^smokeregister/(?P<sn>\w{12})/$', (DetailSmokeRegister.as_view()), name='detail_smokeregister'),
    url(r'^smokeregister/(?P<sn>\w{12})/edit/$', permission_required('fastrax.add_smokeregister')(UpdateSmokeRegister.as_view()), name='update_smokeregister'),
    url(r'^smokeregister/(?P<sn>\w{12})/delete/$', permission_required('fastrax.delete_smokeregister')(DeleteSmokeRegister.as_view()), name='delete_smokeregister'),
    #url(r'^smokeregister/district/(?P<tla>\w+)/(?P<slug>\D+)/closed/$', (DistrictListSmokeRegisterClosed.as_view()), name='district_list_smokeregister_closed'),
    url(r'^smokeregister/district/(?P<tla>\w+)/(?P<slug>\D+)/$', (DistrictListSmokeRegister.as_view()), name='district_list_smokeregister'),
    url(r'^plusfour/$', (ListPlusFour.as_view()), name='list_plusfour'),
    url(r'^plusfour/create/$', permission_required('fastrax.add_plusfour')(CreatePlusFour.as_view()), name='create_plusfour'),
    url(r'^plusfour/(?P<pk>\d+)/$', (PrintPlusFour.as_view()), name='print_plusfour'),
    url(r'^plusfour/(?P<pk>\d+)/edit/$', permission_required('fastrax.add_plusfour')(UpdatePlusFour.as_view()), name='update_plusfour'),
    url(r'^plusfour/(?P<pk>\d+)/delete/$', permission_required('fastrax.delete_plusfour')(DeletePlusFour.as_view()), name='delete_plusfour'),
    url(r'^plusfour/(?P<pk>\d+)/status/$', permission_required('fastrax.delete_plusfour')(StatusPlusFour.as_view()), name='status_plusfour'),
    (r'^(?P<sn>\w{12})/alt/$', 'snalt'),
    (r'^(?P<sn>\w{12})/$', 'sn'),
    (r'^(?P<sn>\w{12})/edit/$', 'snedit'),
    (r'^(?P<sn>\w{12})/dyn/$', 'sndyn'),
    (r'^(?P<sn>\w{12})/registerlike/$', 'snregisterlike'),
    (r'^plan/$', 'plan'),
    (r'^(?P<sn>\w{12})/plan/$', 'snplan'),
    (r'^(?P<sn>\w{12})/plan2/$', 'snplan2'),
    (r'^(?P<sn>\w{12})/(?P<pn>\d{2})/alt/$', 'snpnalt'),
    (r'^(?P<sn>\w{12})/(?P<pn>\d{2})/$', 'snpn'),
    #(r'^result/$', 'result'),
    (r'^(?P<sn>\w{12})/(?P<pn>\d{2})/result/$', 'snpnresult'),
    (r'^(?P<sn>\w{12})/(?P<pn>\d{2})/result1/$', 'snpnresult1'),
    (r'^(?P<sn>\w{12})/(?P<pn>\d{2})/noresult/$', 'snpnnoresult'),
    (r'^odf/district/$', 'odfdistrict'),
    (r'^odf/REGISTERDATETIME(?P<year>\d{4})(?P<mo>\d{2})(?P<da>\d{2})(?P<hr>\d{2})(?P<mi>\d{2}).txt$', 'odfamtxt'),
    (r'^odf/REGISTERDATETIME(?P<year>\d{4})(?P<mo>\d{2})(?P<da>\d{2}).txt$', 'odfdatetxt'),
    (r'^odf/REGISTERDATETIME(?P<year>\d{4})(?P<mo>\d{2}).txt$', 'odfmotxt'),
    (r'^odf/REGISTERDATETIME(?P<year>\d{4}).txt$', 'odfyrtxt'),
    (r'^odf/REGISTERDATETIME(?P<year>\d{4})(?P<mo>\d{2})(?P<da>\d{2}).json$', 'odfjson'),
    (r'^odf/REGISTERDATETIME(?P<year>\d{4})(?P<mo>\d{2}).json$', 'odfjson'),
    (r'^odf/REGISTERDATETIME(?P<year>\d{4}).json$', 'odfjson'),
    (r'^odf/daily.json$', 'odfjsondaily'),
    (r'^odf/(?P<year>\d{4})/(?P<mo>\d{2})/(?P<da>\d{2})/$', 'odfdate'),
    (r'^odf/(?P<year>\d{4})/(?P<mo>\d{2})/$', 'odfmonth'),
    (r'^odf/(?P<year>\d{4})/$', 'odfyear'),
    (r'^annotated/odf/(?P<year>\d{4})/(?P<mo>\d{2})/(?P<da>\d{2})/$', 'odfandate'),
    (r'^annotated/odf/(?P<year>\d{4})/(?P<mo>\d{2})/$', 'odfanmonth'),
    (r'^annotated/odf/(?P<year>\d{4})/$', 'odfanyear'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/(?P<da>\d{2})/ignition/$', 'date_ignition'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/(?P<da>\d{2})/map/$', 'datemap'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/(?P<da>\d{2})/$', 'date'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/(?P<da>\d{2})/(?P<hr>\d{2})(?P<mi>\d{2})/map/$', 'dateammap'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/(?P<da>\d{2})/(?P<hr>\d{2})(?P<mi>\d{2})/$', 'dateam'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/$', 'month'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/map/$', 'monthmap'),
    (r'^(?P<year>\d{4})/$', 'year'),
    (r'^(?P<year>\d{4})/problems/$', 'yearproblems'),
    (r'^(?P<year>\d{4})/overage/$', 'yearoverage'),
    (r'^(?P<year>\d{4})/map/$', 'yearmap'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/sum/$', 'monthsum'),
    (r'^(?P<year>\d{4})/sum/$', 'yearsum'),
    (r'^(?P<year>\d{4})/(?P<mo>\d{2})/accomp/$', 'monthaccomp'),
    (r'^accomp/accomp-(?P<year>\d{4})-(?P<mo>\d{2}).csv$', 'monthaccompt'),
#    (r'^(?P<year>\d{4})/accomp/$', 'yearaccomp'),
    (r'^(?P<year>\d{4})/accomp/$', 'fiscalaccomp'),
    (r'^accomp/accomp-(?P<year>\d{4})-fiscal.csv$', 'fiscalaccompt'),
    (r'^user/$', 'users'),
    (r'^user/(?P<un>[\w@\.]+)/$', 'user'),
    (r'^user/(?P<un>[\w@\.]+)/closed/$', 'uclosed'),
    (r'^user/(?P<un>[\w@\.]+)/sum/$', 'usersum'),
    (r'^control/$', 'control'),
    (r'^district/$', 'districts'),
    (r'^district/(?P<tn>\w+)/$', 'tla'),
    (r'^district/(?P<tn>\w+)/map/$', 'tlamap'),
    (r'^district/(?P<tn>\w+)/closed/$', 'tclosed'),
    (r'^district/(?P<tn>\w+)/(?P<dn>\D+)/register/$', 'tndnregister'),
    (r'^district/(?P<tn>\w+)/(?P<dn>\D+)/register2/$', 'tndnregister2'),
    (r'^district/(?P<tn>\w+)/(?P<dn>\D+)/register1/$', 'tndnregister1'),
    (r'^district/(?P<tn>\w+)/(?P<dn>\D+)/closed/$', 'dclosed'),
    (r'^district/(?P<tn>\w+)/(?P<dn>\D+)/map/$', 'distmap'),
    (r'^district/(?P<tn>\w+)/(?P<dn>\D+)/test/$', 'test'),
    (r'^district/(?P<tn>\w+)/(?P<dn>\D+)/$', 'district'),
    (r'^transfer/$', 'transfer'),
)